export const colleges = [
  {
    id: "vjti-mumbai",
    name: "VJTI Mumbai",
    fullName: "Veermata Jijabai Technological Institute",
    city: "Mumbai",
    district: "Mumbai",
    type: "Government",
    naacGrade: "A++",
    established: 1887,
    logo: "/colleges/vjti.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 99.8, obc: 99.5, sc: 98.2, st: 96.5 },
      "IT": { open: 99.6, obc: 99.2, sc: 97.8, st: 95.8 },
      "EXTC": { open: 99.2, obc: 98.8, sc: 96.5, st: 94.2 },
      "Mechanical": { open: 98.5, obc: 97.8, sc: 95.2, st: 92.5 },
    },
    rating: 4.8,
    reviewCount: 245,
  },
  {
    id: "ict-mumbai",
    name: "ICT Mumbai",
    fullName: "Institute of Chemical Technology",
    city: "Mumbai",
    district: "Mumbai",
    type: "Government",
    naacGrade: "A++",
    established: 1933,
    logo: "/colleges/ict.png",
    branches: ["Chemical Engineering", "Pharmaceutical", "Food Technology", "Polymer Engineering"],
    cutoffs: {
      "Chemical Engineering": { open: 99.5, obc: 99.1, sc: 97.5, st: 95.2 },
      "Pharmaceutical": { open: 99.2, obc: 98.7, sc: 96.8, st: 94.5 },
    },
    rating: 4.9,
    reviewCount: 189,
  },
  {
    id: "coep-pune",
    name: "COEP Pune",
    fullName: "College of Engineering Pune",
    city: "Pune",
    district: "Pune",
    type: "Government",
    naacGrade: "A++",
    established: 1854,
    logo: "/colleges/coep.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 99.7, obc: 99.3, sc: 98.0, st: 96.2 },
      "IT": { open: 99.4, obc: 99.0, sc: 97.5, st: 95.5 },
      "Mechanical": { open: 98.8, obc: 98.2, sc: 96.0, st: 93.8 },
    },
    rating: 4.8,
    reviewCount: 312,
  },
  {
    id: "pict-pune",
    name: "PICT Pune",
    fullName: "Pune Institute of Computer Technology",
    city: "Pune",
    district: "Pune",
    type: "Aided",
    naacGrade: "A+",
    established: 1983,
    logo: "/colleges/pict.png",
    branches: ["Computer Engineering", "IT", "EXTC"],
    cutoffs: {
      "Computer Engineering": { open: 99.2, obc: 98.7, sc: 97.0, st: 94.8 },
      "IT": { open: 98.8, obc: 98.2, sc: 96.5, st: 94.2 },
    },
    rating: 4.7,
    reviewCount: 278,
  },
  {
    id: "spit-mumbai",
    name: "SPIT Mumbai",
    fullName: "Sardar Patel Institute of Technology",
    city: "Mumbai",
    district: "Mumbai",
    type: "Aided",
    naacGrade: "A+",
    established: 2005,
    logo: "/colleges/spit.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Electronics"],
    cutoffs: {
      "Computer Engineering": { open: 99.0, obc: 98.5, sc: 96.8, st: 94.5 },
      "IT": { open: 98.6, obc: 98.0, sc: 96.2, st: 93.8 },
    },
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: "vjti-nagpur",
    name: "VJTI Nagpur",
    fullName: "Veermata Jijabai Technological Institute Nagpur",
    city: "Nagpur",
    district: "Nagpur",
    type: "Government",
    naacGrade: "A",
    established: 1960,
    logo: "/colleges/vjti-nagpur.png",
    branches: ["Computer Engineering", "IT", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 97.5, obc: 96.8, sc: 94.2, st: 91.5 },
      "IT": { open: 96.8, obc: 96.0, sc: 93.5, st: 90.8 },
    },
    rating: 4.4,
    reviewCount: 98,
  },
  {
    id: "ycce-nagpur",
    name: "YCCE Nagpur",
    fullName: "Yeshwantrao Chavan College of Engineering",
    city: "Nagpur",
    district: "Nagpur",
    type: "Government",
    naacGrade: "A",
    established: 1984,
    logo: "/colleges/ycce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil"],
    cutoffs: {
      "Computer Engineering": { open: 96.5, obc: 95.8, sc: 93.2, st: 90.5 },
      "IT": { open: 95.8, obc: 95.0, sc: 92.5, st: 89.8 },
    },
    rating: 4.3,
    reviewCount: 134,
  },
  {
    id: "wce-sangli",
    name: "WCE Sangli",
    fullName: "Walchand College of Engineering",
    city: "Sangli",
    district: "Sangli",
    type: "Government",
    naacGrade: "A+",
    established: 1947,
    logo: "/colleges/wce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 98.2, obc: 97.5, sc: 95.5, st: 93.2 },
      "IT": { open: 97.5, obc: 96.8, sc: 94.8, st: 92.5 },
    },
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: "gcoe-amravati",
    name: "GCOE Amravati",
    fullName: "Government College of Engineering Amravati",
    city: "Amravati",
    district: "Amravati",
    type: "Government",
    naacGrade: "A",
    established: 1964,
    logo: "/colleges/gcoe.png",
    branches: ["Computer Engineering", "IT", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 95.2, obc: 94.5, sc: 91.8, st: 88.5 },
      "IT": { open: 94.5, obc: 93.8, sc: 91.0, st: 87.8 },
    },
    rating: 4.2,
    reviewCount: 89,
  },
  {
    id: "djsce-mumbai",
    name: "DJSCE Mumbai",
    fullName: "Dwarkadas J. Sanghvi College of Engineering",
    city: "Mumbai",
    district: "Mumbai",
    type: "Unaided",
    naacGrade: "A+",
    established: 1994,
    logo: "/colleges/djsce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical"],
    cutoffs: {
      "Computer Engineering": { open: 98.5, obc: 97.8, sc: 95.8, st: 93.5 },
      "IT": { open: 97.8, obc: 97.0, sc: 95.0, st: 92.8 },
    },
    rating: 4.5,
    reviewCount: 201,
  },
  {
    id: "kj-somaiya-mumbai",
    name: "KJ Somaiya Mumbai",
    fullName: "K. J. Somaiya College of Engineering",
    city: "Mumbai",
    district: "Mumbai",
    type: "Unaided",
    naacGrade: "A+",
    established: 1983,
    logo: "/colleges/kjsomaiya.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Electronics"],
    cutoffs: {
      "Computer Engineering": { open: 98.0, obc: 97.2, sc: 95.2, st: 92.8 },
      "IT": { open: 97.2, obc: 96.5, sc: 94.5, st: 92.0 },
    },
    rating: 4.4,
    reviewCount: 178,
  },
  {
    id: "viit-pune",
    name: "VIIT Pune",
    fullName: "Vishwakarma Institute of Information Technology",
    city: "Pune",
    district: "Pune",
    type: "Unaided",
    naacGrade: "A",
    established: 2002,
    logo: "/colleges/viit.png",
    branches: ["Computer Engineering", "IT", "EXTC"],
    cutoffs: {
      "Computer Engineering": { open: 96.8, obc: 96.0, sc: 93.5, st: 90.8 },
      "IT": { open: 96.0, obc: 95.2, sc: 92.8, st: 90.0 },
    },
    rating: 4.3,
    reviewCount: 145,
  },
];
export const mentors = [
  {
    id: "ganesh-sarode",
    name: "Ganesh Sarode",
    firstName: "Ganesh",
    avatar: "",
    college: "VJTI Mumbai",
    collegeId: "vjti-mumbai",
    branch: "EXTC",
    year: "SY BTech EXTC",
    achievement: "99.21%ile MHTCET",
    bio: "SY BTech EXTC at VJTI Mumbai. Happy to guide CET aspirants on strategy, college selection, and what engineering life is actually like.",
    fullBio: "I scored 99.21 percentile in MHTCET and joined VJTI Mumbai for EXTC (Electronics & Telecommunication). I built this platform because I know how confusing the CET process can be — wrong college choices, no real guidance, just noise. I want to give you honest, practical advice based on my real experience. No scripts, no fake promises.",
    topics: ["CET Strategy", "College Selection", "VJTI Insights", "Study Planning", "CAP Round Guidance"],
    rating: null,
    sessionCount: 0,
    price: 0,
    whatsappLink: "https://chat.whatsapp.com/FT9zIkNqsbt4yNQDDkEGaU",
    available: true,
  },
];



// ⚠️ DEPRECATED: mockTests and papers are superseded by the Supabase PYQ system.
// Keeping empty exports to avoid breaking any leftover imports.
// Real data comes from /api/pyq/papers and /api/pyq/sessions.
export const mockTests: never[] = [];
export const papers: never[] = [];

export const testimonials = [
  {
    id: "1",
    name: "Rohan Patil",
    college: "VJTI Mumbai",
    branch: "Computer Engineering",
    cetScore: "99.45%ile",
    text: "The PYQ practice papers on CET Mentor Hub were exactly like the real exam. Solving them in timed mode really helped me manage pressure during the actual CET.",
    avatar: "RP",
  },
  {
    id: "2",
    name: "Sneha Kulkarni",
    college: "COEP Pune",
    branch: "IT",
    cetScore: "98.92%ile",
    text: "I was confused between VJTI and COEP. One session with Ganesh cleared all my doubts about branch vs college priority. Genuinely helpful, no sugar-coating.",
    avatar: "SK",
  },
  {
    id: "3",
    name: "Aditya Deshmukh",
    college: "PICT Pune",
    branch: "Computer Engineering",
    cetScore: "98.15%ile",
    text: "The subject-wise practice mode helped me identify my weak areas in Chemistry. I improved my score by 15 marks in just 2 weeks of focused practice.",
    avatar: "AD",
  },
  {
    id: "4",
    name: "Priya Sharma",
    college: "SPIT Mumbai",
    branch: "EXTC",
    cetScore: "97.80%ile",
    text: "Best part about CET Mentor Hub is the college predictor — it gave me realistic expectations. The mentor guidance on CAP rounds was invaluable.",
    avatar: "PS",
  },
];


export const districts = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Amravati",
  "Kolhapur",
  "Sangli",
  "Thane",
  "Raigad",
  "Satara",
];

export const branches = [
  "Computer Engineering",
  "IT",
  "EXTC",
  "Mechanical",
  "Civil",
  "Electrical",
  "Chemical Engineering",
  "Electronics",
  "Production",
  "Textile"
];

export const categories = [
  { value: "open", label: "Open" },
  { value: "obc", label: "OBC" },
  { value: "sc", label: "SC" },
  { value: "st", label: "ST" },
  { value: "vj", label: "VJ/NT" },
  { value: "ews", label: "EWS" },
];

export const collegeTypes = ["Government", "Aided", "Unaided"];

export const naacGrades = ["A++", "A+", "A", "B++", "B+", "B"];
