export const colleges = [
  {
    id: "vjti-mumbai",
    name: "VJTI Mumbai",
    fullName: "Veermata Jijabai Technological Institute",
    city: "Mumbai",
    district: "Mumbai",
    type: "Government",
    naacGrade: "A++",
    established: 1887,
    logo: "/colleges/vjti.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 99.8, obc: 99.5, sc: 98.2, st: 96.5 },
      "IT": { open: 99.6, obc: 99.2, sc: 97.8, st: 95.8 },
      "EXTC": { open: 99.2, obc: 98.8, sc: 96.5, st: 94.2 },
      "Mechanical": { open: 98.5, obc: 97.8, sc: 95.2, st: 92.5 },
    },
    rating: 4.8,
    reviewCount: 245,
  },
  {
    id: "ict-mumbai",
    name: "ICT Mumbai",
    fullName: "Institute of Chemical Technology",
    city: "Mumbai",
    district: "Mumbai",
    type: "Government",
    naacGrade: "A++",
    established: 1933,
    logo: "/colleges/ict.png",
    branches: ["Chemical Engineering", "Pharmaceutical", "Food Technology", "Polymer Engineering"],
    cutoffs: {
      "Chemical Engineering": { open: 99.5, obc: 99.1, sc: 97.5, st: 95.2 },
      "Pharmaceutical": { open: 99.2, obc: 98.7, sc: 96.8, st: 94.5 },
    },
    rating: 4.9,
    reviewCount: 189,
  },
  {
    id: "coep-pune",
    name: "COEP Pune",
    fullName: "College of Engineering Pune",
    city: "Pune",
    district: "Pune",
    type: "Government",
    naacGrade: "A++",
    established: 1854,
    logo: "/colleges/coep.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 99.7, obc: 99.3, sc: 98.0, st: 96.2 },
      "IT": { open: 99.4, obc: 99.0, sc: 97.5, st: 95.5 },
      "Mechanical": { open: 98.8, obc: 98.2, sc: 96.0, st: 93.8 },
    },
    rating: 4.8,
    reviewCount: 312,
  },
  {
    id: "pict-pune",
    name: "PICT Pune",
    fullName: "Pune Institute of Computer Technology",
    city: "Pune",
    district: "Pune",
    type: "Aided",
    naacGrade: "A+",
    established: 1983,
    logo: "/colleges/pict.png",
    branches: ["Computer Engineering", "IT", "EXTC"],
    cutoffs: {
      "Computer Engineering": { open: 99.2, obc: 98.7, sc: 97.0, st: 94.8 },
      "IT": { open: 98.8, obc: 98.2, sc: 96.5, st: 94.2 },
    },
    rating: 4.7,
    reviewCount: 278,
  },
  {
    id: "spit-mumbai",
    name: "SPIT Mumbai",
    fullName: "Sardar Patel Institute of Technology",
    city: "Mumbai",
    district: "Mumbai",
    type: "Aided",
    naacGrade: "A+",
    established: 2005,
    logo: "/colleges/spit.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Electronics"],
    cutoffs: {
      "Computer Engineering": { open: 99.0, obc: 98.5, sc: 96.8, st: 94.5 },
      "IT": { open: 98.6, obc: 98.0, sc: 96.2, st: 93.8 },
    },
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: "vjti-nagpur",
    name: "VJTI Nagpur",
    fullName: "Veermata Jijabai Technological Institute Nagpur",
    city: "Nagpur",
    district: "Nagpur",
    type: "Government",
    naacGrade: "A",
    established: 1960,
    logo: "/colleges/vjti-nagpur.png",
    branches: ["Computer Engineering", "IT", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 97.5, obc: 96.8, sc: 94.2, st: 91.5 },
      "IT": { open: 96.8, obc: 96.0, sc: 93.5, st: 90.8 },
    },
    rating: 4.4,
    reviewCount: 98,
  },
  {
    id: "ycce-nagpur",
    name: "YCCE Nagpur",
    fullName: "Yeshwantrao Chavan College of Engineering",
    city: "Nagpur",
    district: "Nagpur",
    type: "Government",
    naacGrade: "A",
    established: 1984,
    logo: "/colleges/ycce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil"],
    cutoffs: {
      "Computer Engineering": { open: 96.5, obc: 95.8, sc: 93.2, st: 90.5 },
      "IT": { open: 95.8, obc: 95.0, sc: 92.5, st: 89.8 },
    },
    rating: 4.3,
    reviewCount: 134,
  },
  {
    id: "wce-sangli",
    name: "WCE Sangli",
    fullName: "Walchand College of Engineering",
    city: "Sangli",
    district: "Sangli",
    type: "Government",
    naacGrade: "A+",
    established: 1947,
    logo: "/colleges/wce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 98.2, obc: 97.5, sc: 95.5, st: 93.2 },
      "IT": { open: 97.5, obc: 96.8, sc: 94.8, st: 92.5 },
    },
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: "gcoe-amravati",
    name: "GCOE Amravati",
    fullName: "Government College of Engineering Amravati",
    city: "Amravati",
    district: "Amravati",
    type: "Government",
    naacGrade: "A",
    established: 1964,
    logo: "/colleges/gcoe.png",
    branches: ["Computer Engineering", "IT", "Mechanical", "Civil", "Electrical"],
    cutoffs: {
      "Computer Engineering": { open: 95.2, obc: 94.5, sc: 91.8, st: 88.5 },
      "IT": { open: 94.5, obc: 93.8, sc: 91.0, st: 87.8 },
    },
    rating: 4.2,
    reviewCount: 89,
  },
  {
    id: "djsce-mumbai",
    name: "DJSCE Mumbai",
    fullName: "Dwarkadas J. Sanghvi College of Engineering",
    city: "Mumbai",
    district: "Mumbai",
    type: "Unaided",
    naacGrade: "A+",
    established: 1994,
    logo: "/colleges/djsce.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical"],
    cutoffs: {
      "Computer Engineering": { open: 98.5, obc: 97.8, sc: 95.8, st: 93.5 },
      "IT": { open: 97.8, obc: 97.0, sc: 95.0, st: 92.8 },
    },
    rating: 4.5,
    reviewCount: 201,
  },
  {
    id: "kj-somaiya-mumbai",
    name: "KJ Somaiya Mumbai",
    fullName: "K. J. Somaiya College of Engineering",
    city: "Mumbai",
    district: "Mumbai",
    type: "Unaided",
    naacGrade: "A+",
    established: 1983,
    logo: "/colleges/kjsomaiya.png",
    branches: ["Computer Engineering", "IT", "EXTC", "Mechanical", "Electronics"],
    cutoffs: {
      "Computer Engineering": { open: 98.0, obc: 97.2, sc: 95.2, st: 92.8 },
      "IT": { open: 97.2, obc: 96.5, sc: 94.5, st: 92.0 },
    },
    rating: 4.4,
    reviewCount: 178,
  },
  {
    id: "viit-pune",
    name: "VIIT Pune",
    fullName: "Vishwakarma Institute of Information Technology",
    city: "Pune",
    district: "Pune",
    type: "Unaided",
    naacGrade: "A",
    established: 2002,
    logo: "/colleges/viit.png",
    branches: ["Computer Engineering", "IT", "EXTC"],
    cutoffs: {
      "Computer Engineering": { open: 96.8, obc: 96.0, sc: 93.5, st: 90.8 },
      "IT": { open: 96.0, obc: 95.2, sc: 92.8, st: 90.0 },
    },
    rating: 4.3,
    reviewCount: 145,
  },
];
export const mentors = [
  {
    id: "ganesh-sarode",
    name: "Ganesh Sarode",
    firstName: "Ganesh",
    avatar: "",
    college: "VJTI Mumbai",
    collegeId: "vjti-mumbai",
    branch: "Engineering",
    year: "2nd Year",
    achievement: "99.21%ile MHTCET",
    bio: "Currently at VJTI Mumbai. Happy to guide CET aspirants on strategy, college selection, and what engineering life is actually like.",
    fullBio: "I scored 99.21 percentile in MHTCET and joined VJTI Mumbai. I built this platform because I know how confusing the CET process can be — wrong college choices, no real guidance, just noise. I want to give you honest, practical advice based on my real experience. No scripts, no fake promises.",
    topics: ["CET Strategy", "College Selection", "VJTI Insights", "Study Planning", "CAP Round Guidance"],
    rating: null,
    sessionCount: 0,
    price: 0,
    available: true,
  },
];

// export const mentors = [
//   {
//     id: "arjun-s",
//     name: "Arjun S.",
//     firstName: "Arjun",
//     avatar: "/mentors/arjun.jpg",
//     college: "VJTI Mumbai",
//     collegeId: "vjti-mumbai",
//     branch: "Computer Engineering",
//     year: "3rd Year",
//     achievement: "99.4%ile MHTCET",
//     bio: "Passionate about helping juniors crack CET. Specialized in Physics and Maths problem-solving strategies.",
//     fullBio: "I cracked MHTCET with 99.4 percentile and got into my dream college VJTI. During my preparation, I struggled a lot with time management and choosing the right resources. Now I want to help students avoid these mistakes and achieve their goals. I specialize in Physics numerical solving and Maths shortcuts.",
//     topics: ["Physics Numericals", "Maths Shortcuts", "Time Management", "CET Strategy"],
//     rating: 4.9,
//     sessionCount: 156,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "priya-m",
//     name: "Priya M.",
//     firstName: "Priya",
//     avatar: "/mentors/priya.jpg",
//     college: "ICT Mumbai",
//     collegeId: "ict-mumbai",
//     branch: "Chemical Engineering",
//     year: "2nd Year",
//     achievement: "98.1%ile MHTCET",
//     bio: "Chemistry lover who makes organic reactions fun! Can help with college selection too.",
//     fullBio: "Chemistry was my favorite subject and it helped me score well in CET. I know many students find organic chemistry confusing, but with the right approach, it becomes easy. I also have good knowledge about chemical engineering colleges and can guide you on branch selection.",
//     topics: ["Organic Chemistry", "Inorganic Chemistry", "College Selection", "Branch Guidance"],
//     rating: 4.8,
//     sessionCount: 98,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "rahul-d",
//     name: "Rahul D.",
//     firstName: "Rahul",
//     avatar: "/mentors/rahul.jpg",
//     college: "COEP Pune",
//     collegeId: "coep-pune",
//     branch: "Mechanical Engineering",
//     year: "4th Year",
//     achievement: "JEE AIR 3200",
//     bio: "JEE Advanced qualified! Can help with both JEE and CET preparation strategies.",
//     fullBio: "I cleared JEE Advanced with AIR 3200 and also had a backup plan with MHTCET. I understand the pressure of managing both exams. My sessions focus on building strong fundamentals that help in both exams. I can also guide on IIT vs NIT vs State college decisions.",
//     topics: ["JEE Preparation", "Physics Concepts", "Dual Exam Strategy", "IIT vs NIT Guidance"],
//     rating: 4.9,
//     sessionCount: 234,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "sneha-k",
//     name: "Sneha K.",
//     firstName: "Sneha",
//     avatar: "/mentors/sneha.jpg",
//     college: "PICT Pune",
//     collegeId: "pict-pune",
//     branch: "IT",
//     year: "3rd Year",
//     achievement: "99.1%ile MHTCET",
//     bio: "From average student to PICT IT! I know the struggle and can help you overcome it.",
//     fullBio: "I wasn't a topper in school. In fact, I was an average student until 11th. But with the right strategy and consistent effort, I managed to crack CET with 99.1 percentile. I understand the mindset of students who feel they can't do it. Let me help you prove yourself wrong!",
//     topics: ["Study Planning", "Motivation", "Weak to Strong Strategy", "Mock Test Analysis"],
//     rating: 4.7,
//     sessionCount: 87,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "amit-p",
//     name: "Amit P.",
//     firstName: "Amit",
//     avatar: "/mentors/amit.jpg",
//     college: "SPIT Mumbai",
//     collegeId: "spit-mumbai",
//     branch: "Computer Engineering",
//     year: "2nd Year",
//     achievement: "98.8%ile MHTCET",
//     bio: "Coding enthusiast and CET cracker. Can guide on CS branch and placement prep too.",
//     fullBio: "Apart from cracking CET, I've been coding since 10th standard. I can not only help you with your exam preparation but also give you a glimpse of what computer engineering is actually about. Understanding this might help you decide if CS is the right branch for you.",
//     topics: ["Maths Problem Solving", "CS Branch Insights", "Coding Introduction", "Career Guidance"],
//     rating: 4.6,
//     sessionCount: 65,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "neha-r",
//     name: "Neha R.",
//     firstName: "Neha",
//     avatar: "/mentors/neha.jpg",
//     college: "VJTI Mumbai",
//     collegeId: "vjti-mumbai",
//     branch: "EXTC",
//     year: "4th Year",
//     achievement: "99.2%ile MHTCET",
//     bio: "EXTC senior at VJTI. Can help with electronics concepts and CET Physics.",
//     fullBio: "Electronics and communication is a fascinating branch that many students overlook. I chose EXTC at VJTI and I'm loving it. If you're confused between CS, IT, and EXTC, I can help you understand the differences. My CET preparation focused heavily on physics, which I can help you with.",
//     topics: ["Physics Concepts", "EXTC vs CS vs IT", "Electronics Basics", "VJTI Campus Life"],
//     rating: 4.8,
//     sessionCount: 112,
//     price: 49,
//     available: true,
//   },
//   {
//     id: "rohan-g",
//     name: "Rohan G.",
//     firstName: "Rohan",
//     avatar: "/mentors/rohan.jpg",
//     college: "WCE Sangli",
//     collegeId: "wce-sangli",
//     branch: "Computer Engineering",
//     year: "3rd Year",
//     achievement: "98.5%ile MHTCET",
//     bio: "From small town to top college. Distance learning strategies specialist.",
//     fullBio: "I'm from a small town in Maharashtra where coaching facilities were limited. I relied heavily on online resources and self-study. If you're in a similar situation, I can share strategies that worked for me. Don't let your location be a barrier to your dreams!",
//     topics: ["Self-Study Strategies", "Online Resources", "Small Town to Big College", "Time Management"],
//     rating: 4.7,
//     sessionCount: 78,
//     price: 49,
//     available: false,
//   },
//   {
//     id: "kavya-s",
//     name: "Kavya S.",
//     firstName: "Kavya",
//     avatar: "/mentors/kavya.jpg",
//     college: "COEP Pune",
//     collegeId: "coep-pune",
//     branch: "Computer Engineering",
//     year: "2nd Year",
//     achievement: "99.6%ile MHTCET",
//     bio: "Near-perfect percentile holder. Exam strategy and last-month preparation expert.",
//     fullBio: "I scored 99.6 percentile in MHTCET and got CS at COEP. My strength was my exam strategy - knowing what to attempt first, time allocation, and avoiding silly mistakes. If your concepts are clear but scores aren't reflecting it, I can help you bridge that gap.",
//     topics: ["Exam Strategy", "Time Management", "Last Month Preparation", "Avoiding Silly Mistakes"],
//     rating: 4.9,
//     sessionCount: 143,
//     price: 49,
//     available: true,
//   },
// ];

export const mockTests = [
  {
    id: "physics-mechanics",
    subject: "Physics",
    topic: "Mechanics",
    questions: 30,
    duration: 45,
    difficulty: "Medium",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "chemistry-organic",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    questions: 25,
    duration: 40,
    difficulty: "Hard",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "maths-calculus",
    subject: "Mathematics",
    topic: "Calculus",
    questions: 30,
    duration: 50,
    difficulty: "Hard",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "physics-electro",
    subject: "Physics",
    topic: "Electromagnetism",
    questions: 25,
    duration: 40,
    difficulty: "Medium",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "chemistry-physical",
    subject: "Chemistry",
    topic: "Physical Chemistry",
    questions: 30,
    duration: 45,
    difficulty: "Medium",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "maths-algebra",
    subject: "Mathematics",
    topic: "Algebra",
    questions: 25,
    duration: 40,
    difficulty: "Easy",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "full-mock-1",
    subject: "Full Mock",
    topic: "MHTCET Pattern",
    questions: 150,
    duration: 180,
    difficulty: "Medium",
    attempts: 0,
    avgScore: 0,
  },
  {
    id: "full-mock-2",
    subject: "Full Mock",
    topic: "JEE Mains Pattern",
    questions: 90,
    duration: 180,
    difficulty: "Hard",
    attempts: 0,
    avgScore: 0,
  },
];
export const testimonials: never[] = [];
// export const testimonials = [
//   {
//     id: 1,
//     name: "Aditya Sharma",
//     college: "Now at VJTI CS",
//     quote: "Arjun bhaiya's tips helped me improve my physics score by 40 marks in just 2 months. Best 49 rupees spent!",
//     rating: 5,
//     avatar: "/testimonials/aditya.jpg",
//   },
//   {
//     id: 2,
//     name: "Pooja Patil",
//     college: "Now at COEP IT",
//     quote: "The college predictor was spot on! It predicted my admission perfectly. Highly recommend to all CET aspirants.",
//     rating: 5,
//     avatar: "/testimonials/pooja.jpg",
//   },
//   {
//     id: 3,
//     name: "Rohan Deshmukh",
//     college: "Now at PICT CS",
//     quote: "Mock tests here are so close to actual CET pattern. Practiced 15+ tests and it really boosted my confidence.",
//     rating: 5,
//     avatar: "/testimonials/rohan.jpg",
//   },
// ];

export const districts = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Amravati",
  "Kolhapur",
  "Sangli",
  "Thane",
  "Raigad",
  "Satara",
];

export const branches = [
  "Computer Engineering",
  "IT",
  "EXTC",
  "Mechanical",
  "Civil",
  "Electrical",
  "Chemical Engineering",
  "Electronics",
  "Production",
  "Textile"
];

export const categories = [
  { value: "open", label: "Open" },
  { value: "obc", label: "OBC" },
  { value: "sc", label: "SC" },
  { value: "st", label: "ST" },
  { value: "vj", label: "VJ/NT" },
  { value: "ews", label: "EWS" },
];

export const collegeTypes = ["Government", "Aided", "Unaided"];

export const naacGrades = ["A++", "A+", "A", "B++", "B+", "B"];
